namespace retro {
enum class File {
  PNG,
  JPEG,
  BMP,
  GIF,
  TIF,
  XPM,
  TGA,
  LBM,
  PCX,
  PNM,
  SVG,
  WEBP
};
enum class Error {
  SUCCESS,
  FAILED_UNDEFINED, 
  FAILED_WRONG_FILE_FORMAT,
  FAILED_UNSUPPORED_FILE_FORMAT,
  FAILED_TO_FIND_FILE,
  FAILED_TO_READ_FILE,
  FAILED_TO_WRITE_FILE,
  FAILED_TO_OPEN_FILE,
  FAILED_VAR_WAS_PASSED_AS_NULL,
  FAILED_RAN_OUT_OF_MEMORY,
  FAILED_LOGICAL_MATH_ERROR,
  FAILED_LOGICAL_ERROR,
  FAILED_EMULATION_BECAME_INACCURATE,
  FAILED_EMULATION_HALTED,
  FAILED_USED_SYSTEM_CALL_ON_UNSUPPORTED_OS_WINDOWS,
  FAILED_USED_SYSTEM_CALL_ON_UNSUPPORTED_OS_APPLE,
  FAILED_USED_SYSTEM_CALL_ON_UNSUPPORTED_OS_LINUX,
  FAILED_USED_SYSTEM_CALL_ON_UNSUPPORTED_OS_ANDROID,
  FAILED_UNSUPPORTED_OPCODE_CALLED,
};
}
